### ISSUE TITLE
EMD score from stc

### ISSUE THREAD

**Issue by anujanegi** [braindatalab/BSI-Zoo#19]
Added EMD score for metrics using the true and estimated stc using this [ref](https://github.com/PABannier/automatic_hp_selection_for_meg/blob/main/scripts/generate_data_simulated.py#L93).

1. The resulting scores are all over the range. How to normalize something like this? 
2. Also, how to think about this emd score intuitively, given that we don't give any geometry info.

@AliHashemi-ai  anything to add?

@agramfort

**Comment by agramfort** [comment]
what ground metric are you using?

if your ground metric is in milimeters then your EMD output is in milimeters.
You can make this somehow intuitive.

you can look at figure 1 in https://arxiv.org/pdf/1910.01914.pdf and figure 4 2nd row

let me know if it's not clearn

**Comment by agramfort** [comment]
are we making progress here @anujanegi @AliHashemi-ai ?
