### ISSUE TITLE
Add extreme estimator alpha values in CV grid

### ISSUE THREAD

**Issue by anujanegi** [braindatalab/BSI-Zoo#47]
- [x] all methods
- [x] diag noise only
- [x] extreme noise case
- [x] 3 runs, 1 subjects

**Comment by anujanegi** [comment]
For fixed orientation:

![image](https://user-images.githubusercontent.com/29161453/210082132-25e6ca12-68d5-4d2a-8460-bceef1c4c9e1.png)
![image](https://user-images.githubusercontent.com/29161453/210082155-7efb9a6a-3aa0-48a0-a902-0b8870be1c89.png)
![image](https://user-images.githubusercontent.com/29161453/210082168-eec4f0ca-b33d-47fd-9e2f-d8e32f8de982.png)
![image](https://user-images.githubusercontent.com/29161453/210082180-9033644a-8235-44c8-88a3-63102a6a523b.png)

**Comment by anujanegi** [comment]
For free orientation:

![image](https://user-images.githubusercontent.com/29161453/210082262-bb69e0e8-911f-461b-84ef-40b299584591.png)
![image](https://user-images.githubusercontent.com/29161453/210082272-26a1aeff-34b4-4869-bbbd-45b502dac51f.png)
![image](https://user-images.githubusercontent.com/29161453/210082280-8814f63a-3f37-4956-a838-e6f2663a4fa2.png)
![image](https://user-images.githubusercontent.com/29161453/210082304-cf04bf39-69d4-4a52-8134-1ef1935857ad.png)

**Comment by anujanegi** [comment]
@agramfort @AliHashemi-ai

**Comment by agramfort** [comment]
@anujanegi don't you think there is something weird in the free ori case? anything you see now and that looks better than before @anujanegi ?

**Comment by anujanegi** [comment]
- [ ] expand the alpha grid
- [ ] 1 other and 2 subj
- [ ] 5 runs

**Comment by anujanegi** [comment]
Results for the above-mentioned benchmark run:

**for fixed orientation**
![2a44f93b-9014-4a48-b2e3-5db58daa3ad5](https://user-images.githubusercontent.com/29161453/223492204-dd6bcbac-7a5e-4095-b932-2a01ca9bada7.png)
![0bf827c4-d010-4d3e-b2ea-df958e31d5a9](https://user-images.githubusercontent.com/29161453/223492271-dd432d7a-f1a1-4003-92a6-92a9a1b56bbf.png)
![8e145733-ca19-47a9-b53f-0de01354c0db](https://user-images.githubusercontent.com/29161453/223492329-4311ca79-a022-4f67-b6db-61f8b93da604.png)
![3eabbe2e-35f5-474e-a649-169d44093287](https://user-images.githubusercontent.com/29161453/223492415-6ae0cb7b-3353-4da4-86e8-a089446bc3cd.png)


**for free orientation**
![2d78ab4f-297e-4cbc-a2b1-21f4111a8cc3](https://user-images.githubusercontent.com/29161453/223492491-d3916ed7-c801-4a56-b6c0-5df94a47d06c.png)
![364e5334-7f9d-4d6e-91eb-e177f93b72e3](https://user-images.githubusercontent.com/29161453/223493660-08aedf61-ed4e-4f98-b384-19a362372ef9.png)
![f5e69a73-3788-48e5-97ad-c8d93898caec](https://user-images.githubusercontent.com/29161453/223493682-1fd6e037-6b47-4bc1-b7e1-8d67a49ffc2b.png)

![250cfeb0-ab8e-4e7c-936e-b2f8d5dcb6c9](https://user-images.githubusercontent.com/29161453/223493704-e5455559-418f-42ea-8efc-9e8b46d54e63.png)

**Comment by anujanegi** [comment]
The estimator alpha grid was: ([0.66287032, 0.43939706, 0.29126327, 0.19306977, 0.12798022,
              0.08483429, 0.05623413, 0.03727594, 0.02470911, 0.01637894,
              0.01085711, 0.00719686, 0.00477058, 0.00316228])

**Comment by agramfort** [comment]
what do you see? does it seem that it fixes some issues raised before?

**Comment by agramfort** [comment]
what do you see ? does it seem reasonable?

**Comment by anujanegi** [comment]
What makes sense:

- spatial CV picks higher alpha for free ori and small alpha for fiexd ori.
- lower errors in fixed than free 

I think alpha range can be further expanded on the right (especially for free case)
