### ISSUE TITLE
Add eLORETA 

### ISSUE THREAD

**Issue by anujanegi** [braindatalab/BSI-Zoo#54]
we need another linear estimator in the pipeline

**Comment by anujanegi** [comment]
for ref: https://github.com/mne-tools/mne-python/blob/main/mne/minimum_norm/_eloreta.py

**Comment by agramfort** [comment]
@anujanegi here is a notebook that should help https://gist.github.com/agramfort/0cb957aa1458fb2dc1f27bbad54cbb74

**Comment by anujanegi** [comment]
it's here @AliHashemi-ai

**Comment by AliHashemi-ai** [comment]
> it's here @AliHashemi-ai



> it's here @AliHashemi-ai

I see it now. Thanks @anujanegi
